FROM golang

WORKDIR /app/seecret_keeper_service

COPY . .

RUN go mod tidy -v && \
    CGO_ENABLED=0 go build -o SECRET_KEEPER_SERVICE \
    ./.

ENTRYPOINT ["/app/seecret_keeper_service/SECRET_KEEPER_SERVICEE"]