FROM golang

WORKDIR /app/configurator_service

COPY . .

RUN go mod tidy -v && \
    CGO_ENABLED=0 go build -o CONFIGURATOR_SERVICE \
    ./.

ENTRYPOINT ["/app/configurator_service/CONFIGURATOR_SERVICE"]